[package]
name = "touhou"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
touhou-macros = { path = "../touhou-macros" }
time = { version = "0.3.21", features = ["local-offset", "serde-human-readable"] }
tokio = { version = "1.28.2", features = ["full"] }
sqlx = { version = "0.6", features = [ "runtime-tokio-rustls", "sqlite", "time", "offline" ] }
anyhow = { version = "1.0.71", features = ["backtrace"] }
byteorder = "1.4.3"
serde = { version = "1.0.163", features = ["derive"] }
futures = "0.3.28"
sysinfo = "0.29.7"
thiserror = "1.0.44"
