newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true

unstable_features = true
version = "Two"

reorder_imports = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
