[package]
name = "touhou-macros"
version = "0.1.0"
edition = "2021"

[lib]
name = "touhou_macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["extra-traits"] }
proc-macro2 = "1.0"